### ISSUE TITLE
Not compilable

### ISSUE THREAD

**Issue by WinKarbik** [kosign64/aurora#1]
CMakeFiles/remote_control_server_node.dir/src/remote_control_server/main.cpp.o: In function `main':
main.cpp:(.text+0x7d): undefined reference to `NodeQt::quit()'
CMakeFiles/remote_control_server_node.dir/src/remote_control_server/nodeqt.cpp.o: In function `NodeQt::run()':
nodeqt.cpp:(.text+0x7ea): undefined reference to `NodeQt::quit()'
CMakeFiles/remote_control_server_node.dir/remote_control_server_node_automoc.cpp.o: In function `NodeQt::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
remote_control_server_node_automoc.cpp:(.text+0x245): undefined reference to `NodeQt::setVelocity(double)'
remote_control_server_node_automoc.cpp:(.text+0x26d): undefined reference to `NodeQt::setSteeringAngle(double)'
collect2: error: ld returned 1 exit status
aurora/CMakeFiles/remote_control_server_node.dir/build.make:175: recipe for target '/home/unior/catkin_ws/devel/lib/aurora/remote_control_server_node' failed
make[2]: *** [/home/unior/catkin_ws/devel/lib/aurora/remote_control_server_node] Error 1
CMakeFiles/Makefile2:1579: recipe for target 'aurora/CMakeFiles/remote_control_server_node.dir/all' failed
make[1]: *** [aurora/CMakeFiles/remote_control_server_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Any idea to fix?

**Comment by kosign64** [comment]
Hello, did you install all dependencies, including Qt 5.x? Which version of ROS do you use? You can remove all aurora folders from build and devel directories in your workspace and try to rebuild it again using catkin_make. Unfortunately, I don't have Aurora Unior robot anymore. Originally I used Ubuntu 14.04 with ROS Indigo and it worked without any problem. I have just tried to build this project with Debian 9.4, ROS Lunar, Qt 5.10.1, depthimage_to_laserscan from here https://github.com/ros-perception/depthimage_to_laserscan, ur_hardware_driver from here https://github.com/avrora-robotics/ur_hardware_driver and other packages from official ROS repository. I only had to replace CATKIN_INCLUDE_DIRS variable in CMakeLists.txt with catkin_INCLUDE_DIRS in order to build it successfully (without that replacement there was an error "fatal error: ros/ros.h: No such file or directory"). I can not check if it works properly or not without the robot, but at least it is built successfully.

**Comment by kosign64** [comment]
Also you may need to add path to your Qt installation to your PATH variable. (I do it in my .zshrc file with the following line: export PATH=/home/konstantin/programs/Qt/5.10.1/gcc_64/bin:$PATH . If you use bash you can add similar line to your .bashrc file)

**Comment by WinKarbik** [comment]
I am use ubuntu 16.04 with ros kinetic, all dependencies installed, after reverting https://github.com/kosign64/aurora/commit/5c3428cfb47e7a79dc6e9212da13e25b0be31191 it's compilable.
"Also you may need to add path to your Qt installation to your PATH variable" It doesn't help. "I only had to replace CATKIN_INCLUDE_DIRS variable in CMakeLists.txt with catkin_INCLUDE_DIRS in order to build it " I have done this too, but get error that I write. Do you speak Russia? Any contacts with you, not git?

**Comment by kosign64** [comment]
Yes, I can speak Russian. You can contact me in vk.com here https://vk.com/id953415
